### PR TITLE
Add Laravel 6.0 compatibility.

### LINKED ISSUE #24: Laravel 6.0 Compatibility
Adding this as a placeholder to track compatibility until it gets update. I will try to submit a PR, if I can find time. Thanks! :)

### PR DESCRIPTION
**Pull request by mikebronner**
Fixes #24 

Unable to install the latest (compatible) version without these changes to composer dependency versions of the Illuminate packages.

### CODE REVIEW

**Comment by mikebronner** [comment]
@jenssegers Hi Jens, I know you're pretty busy. Would you have some time in the near future to review this PR? Would help tremendously to allow me to upgrade my packages to provide Laravel 6 support.

**Comment by jenssegers** [comment]
The phpunit bump makes most of the travis tests fail it seems. Can we try not bumping the phpunit version and see how it handles older PHP versions?

**Comment by mikebronner** [comment]
@jenssegers Ah, that worked! :)

**Comment by mikebronner** [comment]
@jenssegers Would you consider removal of PHP 5.4 and 5.5 in the travis config?

**Comment by jenssegers** [comment]
@mikebronner yes there's no point in supporting those any longer. Do you feel like adding that to this PR or do you prefer me to do that after merging?

**Comment by mikebronner** [comment]
@jenssegers No problem, I can take care of that. Should we remove HHVM as well, as it is failing?

**Comment by jenssegers** [comment]
@mikebronner Yes remove HHVM as well 👍 🥇

**Comment by mikebronner** [comment]
Woot! All ☘️

**Comment by jenssegers** [comment]
Thanks @mikebronner!

**Pull request merged**
