### PR TITLE
Use GitHub actions

### PR DESCRIPTION
**Pull request by Smolevich**
- Fix binary name for php-coveralls 
- Write config for using Github actions as CI. [Docs](https://help.github.com/en/articles/configuring-a-workflow)

If use prepared docker image with needed dependencies(Composer, xdebug for coveralls) for Ci time build can be increased

For functionality coveralls should set env variables `COVERALLS_RUN_LOCALLY=1` and `COVERALLS_REPO_TOKEN=<your_token>` in UI

### CODE REVIEW

**Comment by Smolevich** [comment]
@jenssegers, can you review please?

**Comment by Smolevich** [comment]
@jenssegers, any updates?

**Comment by Smolevich** [comment]
@jenssegers, can you review please?

**Comment by jenssegers** [comment]
@Smolevich I know this coming very late, but do you think this PR needs an update with new things you've learned?

**Comment by Smolevich** [comment]
Ok, i updated

**Pull request merged**
